name = "moe-counter"
main = "dist/worker.js"
compatibility_date = "2024-02-27"
workers_dev = false

[[routes]]
pattern = "counter.nyanko.moe"
custom_domain = true

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "moe-counter"
database_id = "b67b7cd7-809d-4616-84b5-407d6b007c19"
